title: "AI-Based Motion Analysis and Extended Reality for Telemedicine and Rehabilitation (AIMAXR‑TR)"
description: "Special Session at the 6th IEEE International Conference on ICT Solutions for e-Health (ICTS4eHealth 2026), Algarve, Portugal, June 23–26, 2026."

remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
